Fix test incompatibility with zope.interface 5.0
Recent zope.interface versions made Interface.__module__ a readonly
attribute.  Without this fix, tests fail on Python 2.7 with

    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest directive.rst[105]>", line 1, in <module>
        class once_iface(FakeModule):
      File "/home/mg/src/zopefoundation/martian/src/martian/testing.py", line 65, in __init__
        fake_import(cls)
      File "/home/mg/src/zopefoundation/martian/src/martian/testing.py", line 33, in fake_import
        obj.__module__ = module.__name__
    TypeError: readonly attribute

(On Python 3 assignment to a readonly attribute raises an AttributeError
instead, which was already caught.)